name: Release with goreleaser
on:
  push:
    tags:
      - v*.*.*
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    name: goreleaser
    steps:
    - uses: actions/checkout@v4
    - name: Unshallow Fetch
      run: git fetch --prune --unshallow
    - uses: actions/setup-go@v4
      with:
        go-version: '^1.21.1'
    - uses: tibdex/github-app-token@v2
      id: generate_homebrew_token
      with:
        app_id: ${{ secrets.HOMEBREW_APP_ID }}
        private_key: ${{ secrets.HOMEBREW_APP_PRIVKEY }}
    - name: Release via goreleaser
      uses: goreleaser/goreleaser-action@v5
      with:
        distribution: goreleaser
        args: release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        HOMEBREW: ${{ steps.generate_homebrew_token.outputs.token }}

